name: Sync README

on:
  push:
    branches:
      - develop
    paths:
      - 'Casko.AspNetCore.XmlSiteMaps/Package/**'  

jobs:    
  sync-readme:
    runs-on: ubuntu-latest
    env:
        README_PATH: Casko.AspNetCore.XmlSiteMaps/Package/README.md

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Rebase develop onto main
        run: |
          git checkout develop
          git rebase origin/main

      - name: Copy README to Root
        run: cp ${{ env.README_PATH }} README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md

          # Check if there are any changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update README.md from ${{ env.README_PATH }}"
          fi

      - name: Push changes
        run: |
          git push --force-with-lease origin develop
